"use client";

import QRCode from "qrcode";
import { useEffect, useState } from "react";

export function QRCodeSVG({ value, size = 120 }: { value: string; size?: number }) {
  const [svg, setSvg] = useState("");

  useEffect(() => {
    QRCode.toString(value, { type: "svg", width: size, margin: 1 }).then(setSvg);
  }, [value, size]);

  if (!svg) return <div style={{ width: size, height: size }} className="bg-muted rounded" />;
  // SVG is generated by the qrcode library from a safe string value — not from user input
  return <div dangerouslySetInnerHTML={{ __html: svg }} />;
}
